version: '3.7'

volumes:
  mysql-db:
    driver: local
  node_modules:

services:
  db:
    image: mysql:5.7
    container_name: dm_db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  redis:
    image: redis:alpine
    container_name: redis
    ports: ['6379']

  backend:
    container_name: dm_backend
    build: .
    ports:
      - ${BACKEND_PORT}:${BACKEND_INNER_PORT}
      - '9229:9229'
    volumes:
      - .:/app/src
      - /usr/src/app/node_modules
    command: sh -c "npm run dev"
    environment:
      NODE_ENV: development
      MYSQL_HOST: dm_db
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE_NAME: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
      BACKEND_INNER_PORT: ${BACKEND_INNER_PORT}
      # JWT_SECRET: ${JWT_SECRET}

  # phpmyadmin:
  #   container_name: dm_pma
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - ${PMA_PORT}:80
  #   environment:
  #     PMA_HOST: dm_database
  #     PMA_USER: ${MYSQL_USERNAME}
  #     PMA_PASSWORD: ${MYSQL_PASSWORD}
  #   depends_on:
  #     - database
