version: '3.7'

volumes:
  mysql-db:
    driver: local
  node_modules:

services:
  backend:
    container_name: dm_backend
    build: .
    restart: always
    ports:
      - ${BACKEND_PORT}:${BACKEND_INNER_PORT}
      - '9229:9229'
    volumes:
      - .:/app/src
      - /usr/src/app/node_modules
    command: sh -c "rm -rf dist && npm run build && npm run deploy"
    environment:
      NODE_ENV: production
      MYSQL_HOST: dm_db
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE_NAME: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
      BACKEND_INNER_PORT: ${BACKEND_INNER_PORT}
      # JWT_SECRET: ${JWT_SECRET}

  db:
    image: mysql:5.7
    container_name: dm_db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  redis:
    image: redis:alpine
    container_name: redis
    ports: ['6379']

  phpmyadmin:
    container_name: dm_pma
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PMA_PORT}:${PMA_PORT}
    environment:
      PMA_HOST: dm_database
      PMA_USER: ${MYSQL_USERNAME}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
